version: '3.8'
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: express_jwt_demo
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.1
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: 12345678
    ports:
      - "8080:80"
    depends_on:
      - mysql

volumes:
  mysql_data: